name: Build and Release

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main
    tags:
      - '*'

permissions:
  contents: write

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies
        run: composer install

      - name: Run PHPCS
        run: vendor/bin/phpcs

  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  build:
    runs-on: ubuntu-latest
    needs: [phpcs, eslint]
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Composer Install
        run: composer install --no-dev --no-suggest --optimize-autoloader --no-interaction

      - name: Remove unwanted files
        run: |
          find . -type f -name "phpcs.xml" -exec rm -f {} +
          find . -type f -name ".gitignore" -exec rm -f {} +
          find . -type f -name "webpack.config.js" -exec rm -f {} +
          find . -type d -name "node_modules" -exec rm -rf {} +
          find . -type d -name ".github" -exec rm -rf {} +
          find . -type d -name ".git" -exec rm -rf {} +

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            .

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release ${{ github.ref }}

      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: build
          path: release-artifact

      - name: Set Version in PHP File
        run: |
          cd release-artifact
          sed -i "s/Version:.*$/Version: ${{ github.ref_name }}/" colored-admin-post-list.php
          sed -i "s/Stable tag:.*$/Stable tag: ${{ github.ref_name }}/" readme.txt
        shell: bash

      - name: Zip Repository
        run: |
          cd release-artifact
          echo ${{ github.ref_name }}
          zip -r colored-admin-post-list-${{ github.ref_name }}.zip .
          cp colored-admin-post-list-${{ github.ref_name }}.zip colored-admin-post-list.zip
        shell: bash


      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release-artifact/colored-admin-post-list-${{ github.ref_name }}.zip
          asset_name: colored-admin-post-list-${{ github.ref_name }}.zip
          asset_content_type: application/zip

      - name: Upload Release Asset (without version)
        id: upload-release-asset-without-version
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release-artifact/colored-admin-post-list.zip
          asset_name: colored-admin-post-list.zip
          asset_content_type: application/zip

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: |
            release-artifact
  wporg-deploy:
    name: wordpress.org Deploy
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Tagging
        run: |
          cd release-artifact
          sed -i "s/Version:.*$/Version: ${{ github.ref_name }}/" colored-admin-post-list.php
          sed -i "s/Stable tag:.*$/Stable tag: ${{ github.ref_name }}/" readme.txt
        shell: bash
      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: colored-admin-post-list # optional, remove if GitHub repo name matches SVN slug, including capitalization
  wporg-assets-trunk:
    name: Push to trunk
    runs-on: ubuntu-latest
    needs: phpcs
    steps:
      - uses: actions/checkout@master
      - name: WordPress.org plugin asset/readme update
        uses: 10up/action-wordpress-plugin-asset-update@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: colored-admin-post-list
          IGNORE_OTHER_FILES: true